### ISSUE TITLE
functions returning function pointers have invalid definitions

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/wrapture#76]
Definitions of functions that return a function pointer are incorrectly generated, dumping the contents of the TypeSpec hash directly into the code. For example, the spec in `test/fixtures/function_pointer_return.yml` generates the following definition, which is obviously not valid C code.

The specification contents:
```yaml
name: "FunctionPointerReturn"
params:
  - name: "my_string"
    type: "const char *"
return:
  type:
    includes: "overall_inc_1.h"
    function:
      params:
        - type: "int"
        - type: "int"
        - type:
            name: "struct special *"
            includes: "special_inc_1.h"
      return:
        type: "const char *"
wrapped-function:
  name: "underlying_function"
  params:
    - value: "my_string"
```

The generated definition:
```c
const char *( *FunctionPointerReturn( const char *my_string ) )( int, int, struct special * ) {
  return {"includes"=>"overall_inc_1.h", "function"=>{"params"=>[{"type"=>"int"}, {"type"=>"int"}, {"type"=>{"name"=>"struct special *", "includes"=>"special_inc_1.h"}}], "return"=>{"type"=>"const char *"}}} ( underlying_function( my_string ) );
}
```
