### ISSUE TITLE
return value variable declarations incorrect when using keywords

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/wrapture#77]
Return values are incorrectly typed using the wrapture keyword when the return type is given as one. This is most apparent in constructor definitions, which specify the return type so that the equivalent struct pointer can be set appropriately.

For example, the following class specification:
```yaml
name: "TestClass"
namespace: "bug_demo"
equivalent_struct:
  name: "demo"
constructors:
  - wrapped-function:
      name: "wrapped_constructor"
      params:
        - name: "name"
          type: "const char *"
      return:
        type: "equivalent-struct-pointer"
      error-check:
        rules:
          - left-expression: "return-value"
            condition: "equals"
            right-expression: "NULL"
        error-action:
          name: "throw-exception"
          constructor:
            name: "throwMyException"
            params:
              - value: "name"
destructor:
  wrapped-function:
    name: "wrapped_destructor"
    params:
      - value: "equivalent-struct-pointer"
```

Generates this constructor definition, which mistakenly has the keyword as the type of return_val.
```c
TestClass::TestClass( const char *name ) {
  equivalent-struct-pointer return_val;

  this->equivalent = wrapped_constructor( name );

  if( return_val == NULL ){
    throw throwMyException( name );
  }
}
```
