### ISSUE TITLE
invalid return value in constructor error check

### ISSUE THREAD

**Issue by goatshriek** [goatshriek/wrapture#84]
Constructors that require an error check with the equivalent struct itself never assign to the return value before checking it. The test fixture in `test/fixtures/class_with_return_val_in_constructor.yml`, shown here:

```yaml
name: "ClassWithReturnActionInConstructor"
namespace: "wrapture_test"
equivalent-struct:
  name: "irrelevant"
constructors:
  - wrapped-function:
      name: "wrapped_constructor"
      params:
        - name: "name"
          type: "const char *"
      return:
        type: "equivalent-struct-pointer"
      error-check:
        rules:
          - left-expression: "return-value"
            condition: "equals"
            right-expression: "NULL"
        error-action:
          name: "throw-exception"
          constructor:
            name: "throwMyException"
            params:
              - value: "name"
destructor:
  wrapped-function:
    name: "wrapped_destructor"
    params:
      - value: "equivalent-struct-pointer"
```
generates the following definition, which causes a segmentation fault in the check of `return_val`:

```cpp
ClassWithReturnActionInConstructor::ClassWithReturnActionInConstructor( const char *name ) {
  struct irrelevant *return_val;

  this->equivalent = wrapped_constructor( name );

  if( return_val == NULL ){
    throw throwMyException( name );
  }
}
```
